import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/main/Footer";
import ToastProvider from "@/components/ui/ToastProvider";
import { AuthProvider } from "@/components/ui/login/AuthProvider";
import { ChatProvider } from "@/components/ui/chat/ChatProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FreelanceHUB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <div className="min-h-screen bg-bg text-text transition-colors duration-200">
            <AuthProvider>
              <ToastProvider>
                <ChatProvider>
                  <Navbar />
                  {children} 
                </ChatProvider>
              </ToastProvider>
            </AuthProvider>
          </div>
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
