"""empty message

Revision ID: 13e09a05c82f
Revises: 20f4102ed7be
Create Date: 2025-10-02 20:23:49.139147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13e09a05c82f'
down_revision: Union[str, None] = '20f4102ed7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
