"""empty message

Revision ID: 20f4102ed7be
Revises: 2e29cc2389f3
Create Date: 2025-10-02 17:47:35.723585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20f4102ed7be'
down_revision: Union[str, None] = '2e29cc2389f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('id_order', sa.Integer(), nullable=False))
    op.drop_constraint('reviews_ibfk_3', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'orders', ['id_order'], ['id'])
    op.drop_column('reviews', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_ibfk_3', 'reviews', 'orders', ['order_id'], ['id'])
    op.drop_column('reviews', 'id_order')
    # ### end Alembic commands ###
